### ISSUE TITLE
Bug with big size images

### ISSUE THREAD

**Issue by serjo96** [fritz-c/react-image-lightbox#83] opened 2017-10-28 22:36 UTC
If my images has big size like 3840x2160 lightbox just broke and add puts pictures on the sides
https://yadi.sk/i/SeaDwXWf3PBfvK
but if images have 1280 width all work fine
and this demo exmaple images, second image its placekitten.com/4000/3000
https://yadi.sk/i/MOyAnFLb3PBg6E

**code**

```
this.state = {
            modalTrailer: false,
	        trailerKey: '',
	        lightBox: false,
	        imgIndex: 0
        };


 {this.state.lightBox &&
<Lightbox
	mainSrc={'https://image.tmdb.org/t/p/original' + movie.images.backdrops[imgIndex].file_path}
	nextSrc={'https://image.tmdb.org/t/p/original' + movie.images.backdrops[(imgIndex + 1) % movie.images.backdrops.length].file_path}
	prevSrc={'https://image.tmdb.org/t/p/original' + movie.images.backdrops[(imgIndex + movie.images.backdrops.length - 1) % movie.images.backdrops.length].file_path}

	onCloseRequest={() => this.setState({ lightBox: false })}
	onMovePrevRequest={() => this.setState({
	imgIndex: (imgIndex + movie.images.backdrops.length - 1) % movie.images.backdrops.length,
					 })}
	 onMoveNextRequest={() => this.setState({
	 imgIndex: (imgIndex + 1) % movie.images.backdrops.length,
	})}
 />
 }
```

**Comment by fritz-c** [comment] 2018-01-14 01:37
This is the older issue, but as there's one with more info, I'll consider this a duplicate of #91

**Closed by fritz-c** 2018-01-14 01:37 UTC
