### ISSUE TITLE
Lightbox unusable, broken layout when using landscape images

### ISSUE THREAD

**Issue by audifaxdev** [fritz-c/react-image-lightbox#93] opened 2017-12-06 21:40 UTC
# Reporting a Bug?

Lightbox 's image is out of position when resizing to mobile/tablet.

The Larger horizontally the image is the sooner the layout will break when resizing down.
In other words, when using a portrait image, the layout will break at a much smaller device size than
when using a landscape image. In this later case, the layout will break at a much bigger device size

Basically I feel like the whole css has to be reworked. In its state I would not recommend this plugin as it is not usable.

Example with a portrait images, you can see in a small window, the lightbox image gets out of position
<img width="399" alt="screen shot 2017-12-07 at 10 36 08 am" src="https://user-images.githubusercontent.com/9066940/33686749-bfa4eba6-db3a-11e7-96d6-344a11d36561.png">
<img width="1202" alt="screen shot 2017-12-07 at 10 36 14 am" src="https://user-images.githubusercontent.com/9066940/33686754-c13908d0-db3a-11e7-9b0b-4d593ae39606.png">

Example with a landscape image, as you can see even with a 1920px window it's already breaking
<img width="1920" alt="screen shot 2017-12-07 at 10 38 40 am" src="https://user-images.githubusercontent.com/9066940/33686782-da8cd302-db3a-11e7-9feb-f4d7ccb28e07.png">
<img width="1117" alt="screen shot 2017-12-07 at 10 39 45 am" src="https://user-images.githubusercontent.com/9066940/33686822-f749e278-db3a-11e7-955c-c0a0d25b5d80.png">

**Comment by jaminmelville** [comment] 2017-12-09 03:19
I'm getting this issue too

**Comment by corentinrinaldi** [comment] 2017-12-20 14:09
Hey, I don't know if you resolved this bug, but I had the same issue and solved it. This bug was due to a CSS property "max-width: 100%;" applied to all the img (probably a foundation default behavior).
Applying a "max-width: none !important;" on the img ("ril-image-current" class) solved this issue.
Hope it helped !

**Comment by fritz-c** [comment] 2018-01-14 00:50
Going to treat this as a duplicate of #91, based on the description of the issue.
@corentinrinaldi Thanks for the tip, I think you are correct about it. #73 should have fixed the issue.

**Closed by fritz-c** 2018-01-14 00:50 UTC
Labels: investigate
